### ISSUE TITLE
VOC algo backend 

### ISSUE THREAD

**Issue by bhaskar-anil429** [Sensirion/gas-index-algorithm#6]
Hi, we have been trying to use this sensor for the last few weeks. We are confused about the sensor working principle. Our final product will be battery power. This means we have to turn off the sensor while we are not reading the sensor. 
From what we understand, the sensor sets up a new baseline after every few hours.
This means it can be used as a VOC alarm system, but cant be used as a sensor that can read VOC over time.

**Comment by psachs** [comment]
If the sensor is turned off regularly you might be able to use the VOC state to recover the previously determined internal state. Also check the low and ultra-low power modes.
Due to the limitations of MOx sensors, it is currently not possible to turn off the sensor for a long time and reliably recover the previous state of the algorithm.

https://github.com/Sensirion/gas-index-algorithm/blob/master/sensirion_gas_index_algorithm/sensirion_gas_index_algorithm.h#L202
